homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_domain: {}
  customize_glob: {}
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password 

auth:
http:
  api_password: 2dx4bLkuszdDO3yy
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - ::1
frontend:
  javascript_version: latest

config:
updater:
discovery:
#hassio:
conversation:
cloud:
wake_on_lan:
shopping_list:
sun:
logger:
  default: error
system_log:
  max_entries: 100
recorder:
  purge_interval: 30
  purge_keep_days: 4
#  db_url: !secret sql_uri
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - sun
      - zwave
      - calendar
      - camera
      - group
      - zone
      - input_boolean
    entities:
      - binary_sensor.floorplan
      - binary_sensor.workday_sensor
      - binary_sensor.workday_tomorrow
      - sensor.last_boot
      - sensor.utc
      - sensor.time
      - sensor.date
      - sensor.date__time
      - sensor.next_calendar_event
      - sensor.next_calendar_fb_event
      - sensor.online
      - sensor.pws_location
      - sensor.pws_station_id
      - sensor.pws_weather_2d
      - sensor.season

history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - calendar
      - group
      - sun
      - zone
      - zwave
      - input_boolean
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.time
      - sensor.date__time
      - sensor.utc
      - sensor.time_brightness
      - sensor.moon
      - sensor.season
      - sensor.uptime
      - sensor.dark_sky_summary
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      - sensor.home_to_work
      - sensor.i90_to_home
      - sensor.internet
      - sensor.online
      - sensor.piuptime
      - sensor.pws_location
      - sensor.pws_station_id
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.solary_angle
      - sensor.ssl_certificate_expiry
      - sensor.work_to_i90
      - sensor.work_to_transit_rd
      - sensor.home_to_work
      - sensor.i90_to_home
      - sensor.transit_rd_to_home
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_icon
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_summary
      - sensor.next_calendar_event
      - sensor.next_calendar_fb_event

group: !include groups.yaml
automation: !include_dir_merge_list automations
logbook: !include logbook.yaml
light: !include_dir_merge_list lights
scene: !include_dir_list scenes
sensor: !include_dir_merge_list sensors
script: !include_dir_merge_named scripts
#script: !include scripts.yaml
binary_sensor: !include_dir_merge_list binary_sensors
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
#panel_custom: !include panel_custom.yaml

panel_iframe:  
  music:  
    title: 'Music'  
    icon: 'mdi:music-box-outline'  
    url: !secret music_url

#google_assistant:
#  project_id: !secret google_project
#  client_id: !secret google_client_id
#  access_token: !secret google_access_token
#  agent_user_id: !secret google_agent_id
#  api_key: !secret google_api_key
#  exposed_domains:
#    - switch
#    - light
#    - scene
#    - media_player
#    - climate 

alarm_control_panel:
  platform: manual
  name: "House Alarm"
  code: !secret alarm_code
  pending_time: 60
  trigger_time: 40
  disarm_after_trigger: false

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_key_id
    aws_secret_access_key: !secret aws_secret
    voice: Salli

  - platform: google

zone:
  - name: !secret zone_name
    latitude: !secret zone_latitude
    longitude: !secret zone_longitude
    icon: mdi:home
    radius: 200

  - name: !secret zone2_name
    latitude: !secret zone2_latitude
    longitude: !secret zone2_longitude
    icon: mdi:briefcase
    radius: 200

  - name: !secret zone4_name
    latitude: !secret zone4_latitude
    longitude: !secret zone4_longitude
    icon: mdi:car
    radius: 50

  - name: !secret zone5_name
    latitude: !secret zone5_latitude
    longitude: !secret zone5_longitude
    icon: mdi:car
    radius: 50

  - name: !secret zone6_name
    latitude: !secret zone6_latitude
    longitude: !secret zone6_longitude
    icon: mdi:car
    radius: 50

  - name: !secret zone7_name
    latitude: !secret zone7_latitude
    longitude: !secret zone7_longitude
    icon: mdi:gas-station
    radius: 75

variable:  
  last_motion:
    value: 'Unknown'
    restore: true
    attributes:
      icon: mdi:walk
      friendly_name: "Last Motion"

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
 
media_player:
  - platform: pandora

  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

  - platform: roku
#    host: !secret ip_roku2

  - platform: webostv
    host: !secret ip_livingroom_tv 
    name: Living Room TV
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret mac_livingroom_tv

  - platform: vlc
    name: homepi_audio
    arguments: '--alsa-audio-device=hw:0,0'

#  - platform: snapcast
#    host: 127.0.0.1

#  - platform: mpd
#    host: 127.0.0.1
#    port: 6600
#    location: Multi-Room Controller

  - platform: gstreamer
    pipeline: "audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo"

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  client_id: home-assistant-1
  tls_insecure: True
  tls_version: auto

device_tracker:
  - platform: bluetooth_tracker
    request_rssi: True

  - platform: google_maps
    username: !secret google_acct
    password: !secret google_pass
    max_gps_accuracy: 100
    new_device_defaults:
      track_new_devices: true

  - platform: owntracks
    track_new_devices: yes
    waypoints: True
    max_gps_accuracy: 400
    waypoint_whitelist:
      - rd
      - robertphone

  - platform: mqtt
    devices:
      robert_location: 'location/robert'
      sarah_location: 'location/sarah'
      adriana_location: 'location/adriana'
      brayden_location: 'location/brayden'

  - platform: nmap_tracker
    hosts: !secret ip_subnet2
    home_inteval: 5
    interval_seconds: 120
    consider_home: 240
    exclude:
     - !secret ip_gateway
     - !secret ip_hass

  - platform: mikrotik
    host: !secret mikrotik_host 
    username: !secret mikrotik_user
    password: !secret mikrotik_pass

  - platform: mikrotik
    host: !secret capsman_host
    username: !secret capsman_user
    password: !secret capsman_pass

# /dev/ttyACM0
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/libopenzwave-0.3.3-py3.5-linux-armv7l.egg/config
  #polling_interval: 30000
  #device_config: !include zwave_device_config.yaml

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db


climate:
  - platform: zwave
 
notify:
  - platform: html5
    name: homepi.rd3s.com
    gcm_api_key: !secret html5_gcm_key
    gcm_sender_id: !secret html5_gcm_sender

  - platform: webostv
    host: !secret ip_livingroom_tv
    name: livingroom_tv

  - platform: twilio_sms
    name: twilio
    from_number: !secret twilio_number

  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret google_acct
    encryption: starttls
    username: !secret google_acct
    password: !secret google_pass
    recipient:
      - !secret gmail
      - !secret phone_mail
    sender_name: Home Assistant

twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_token

map:

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

#device_sun_light_trigger:
#  light_group: group.presence_lights
#  light_profile: relax
#  device_group: group.presence_devices
#  disable_turn_off: 1

amcrest:
  - host: !secret ip_camera1
    name: front_door
    username: !secret amcrest_user
    password: !secret amcrest_pass
    sensors:
      - motion_detector
  - host: !secret ip_camera2
    name: garage
    username: !secret amcrest_user
    password: !secret amcrest_pass2
    scan_interval: 3
    #sensors:
    #  - motion_detector
    #stream_source: rtsp
    #resolution: low
    #scan_interval: 10
  - host: !secret ip_camera3
    name: back_yard
    username: !secret amcrest_user
    password: !secret amcrest_pass2
    stream_source: rtsp
    resolution: low
    scan_interval: 10

