homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_domain: {}
  customize_glob: {}

frontend:
config:
http:
  # api_password: PASSWORD
updater:
discovery:
#hassio:
conversation:
history:
shopping_list:
sun:

group: !include groups.yaml
automation: !include_dir_merge_list automations
logbook: !include logbook.yaml
light: !include_dir_merge_list lights
scene: !include_dir_list scenes
sensor: !include_dir_merge_list sensors
script: !include_dir_merge_named scripts
binary_sensor: !include_dir_merge_list binary_sensors
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_slider: !include input_slider.yaml

recorder:
  purge_days: 30
  db_url: !secret sql_uri
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

tts:
  - platform: picotts

zone:
  name: !secret zone_name
  latitude: !secret zone_latitude
  longitude: !secret zone_longitude
  icon: mdi:home
  radius: 200

zone 2:
  name: !secret zone2_name
  latitude: !secret zone2_latitude
  longitude: !secret zone2_longitude
  icon: mdi:briefcase
  radius: 200
 
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
 
media_player:
  - platform: pandora

  - platform: webostv
    host: 192.168.88.18
    name: Living Room TV

  - platform: vlc
    name: homepi_audio
    arguments: '--alsa-audio-device=hw:0,0'

  - platform: snapcast
    host: 127.0.0.1

  - platform: mpd
    host: 127.0.0.1
    location: Multi-Room Controller

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
    waypoints: True

  - platform: nmap_tracker
    hosts: 192.168.88.1/24
    home_inteval: 5
    interval_seconds: 120
    consider_home: 240
    exclude:
     - 192.168.88.1
     - 192.168.88.32

  - platform: mikrotik
    host: !secret mikrotik_host
    username: !secret mikrotik_user
    password: !secret mikrotik_pass

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/open-zwave-control-panel/config
  new_entity_ids: true
  polling_interval: 30000
  device_config:
    switch.garage_inside_motion_switch:
      polling_intensity: 1
    switch.front_door_motion_light_switch:
      polling_intensity: 1
  
notify:
  - platform: html5
    name: homepi.rd3s.com
    gcm_api_key: !secret html5_gcm_api
    gcm_sender_id: !secret html5_gcm_sender

  - platform: webostv
    host: 192.168.88.18
    name: livingroom_tv

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
  track_new_calendar: false

amcrest:
  - host: 192.168.88.20
    username: !secret amcrest_user
    password: !secret amcrest_pass
    stream_source: rtsp
    resolution: low
    scan_interval: 5


