light.front_door_light_level:
  polling_intensity: 1
  refresh_value: true
light.dining_room_light_level:
  polling_intensity: 1
  refresh_value: true
light.stairs_light_level:
  polling_intensity: 1
  refresh_value: true
switch.kids_room1_switch:
  polling_intensity: 1
  refresh_value: true
switch.garage_inside_motion_switch:
  polling_intensity: 1
  refresh_value: true
switch.half_bathroom_switch:
  polling_intensity: 1
  refresh_value: true
switch.switch:
  ignored: false
  polling_intensity: 0
