sensor.front_door_light_burglar:
  ignored: false
  polling_intensity: 1
light.front_door_light_level:
  ignored: false
  polling_intensity: 2
light.kitchen_light_level:
  ignored: false
  polling_intensity: 2
light.family_rm_level:
  ignored: false
  polling_intensity: 2
switch.kids_room1_switch:
  ignored: false
  polling_intensity: 2
switch.garage_inside_motion_switch:
  ignored: false
  polling_intensity: 1
