light.kitchen_light_level:
  ignored: false
  polling_intensity: 2
light.family_rm_level:
  ignored: false
  polling_intensity: 2
switch.kids_room1_switch:
  ignored: false
  polling_intensity: 2
zwave.front_door_motion_light:
  ignored: false
  polling_intensity: 1
switch.front_door_motion_light_switch_2:
  ignored: false
  polling_intensity: 1
