#- platform: api_streams
- platform: moon
- platform: season
- platform: uptime
- platform: version

- platform: speedtest
  minute: 30
  hour:
    - 2
    - 6
    - 8
    - 10
    - 12
    - 14
    - 16
    - 18
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 6030

- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /
  - type: memory_free
  - type: processor_use
  - type: network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: last_boot

- platform: time_date
  display_options:
    - 'date_time'
    - 'time'
    - 'date'

- platform: worldclock
  time_zone: Etc/UTC
  name: 'UTC'


