- platform: template
  sensors:
    xboxone:
      friendly_name: 'Xbox One'
      value_template: "{{ 'Online' if is_state('device_tracker.xboxone', 'home') else 'Offline' }}"
    xbox360:
      friendly_name: 'Xbox 360'
      value_template: "{{ 'Online' if is_state('device_tracker.xbox360', 'home') else 'Offline' }}"
    livingroomtv:
      friendly_name: 'Living Room TV'
      value_template: "{{ 'Online' if is_state('device_tracker.livingroomtv', 'home') else 'Offline' }}"
    anapc:
      friendly_name: 'Ana PC'
      value_template: "{{ 'Online' if is_state('device_tracker.family01', 'home') else 'Offline' }}"
    ana_3ds:
      friendly_name: 'Ana 3DS'
      value_template: "{{ 'Online' if is_state('device_tracker.ana_3ds', 'home') else 'Offline' }}"
    braydenpc: 
      friendly_name: 'Brayden PC'
      value_template: "{{ 'Online' if is_state('device_tracker.braydenpc', 'home') else 'Offline' }}"
    brayden_roku:
      friendly_name: 'Brayden Roku'
      value_template: "{{ 'Online' if is_state('device_tracker.roku2_brayden', 'home') else 'Offline' }}"
    brayden_3ds:
      friendly_name: 'Brayden 3DS'
      value_template: "{{ 'Online' if is_state('device_tracker.brayden_3ds', 'home') else 'Offline' }}"
    thermostat_battery:
      friendly_name: 'Thermostat Battery'
      value_template: '{{ states.zwave.thermostat.attributes.battery_level }}'
      unit_of_measurement: '%'
