- platform: template
  sensors:
    next_calendar_event:
      friendly_name: 'Next Event'
      value_template: >
          {{ strptime(states.calendar.slackr31337gmailcom.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A, %B %d") }}:
          {{ states.calendar.slackr31337gmailcom.attributes.message }}
    next_calendar_fb_event:
      friendly_name: 'Facebook'
      value_template: >
          {{ strptime(states.calendar.rob_dunmires_facebook_events.attributes.start_time, "%Y-%m-%d %H:%M:%S").strftime("%A, %B %d") }}:
          {{ states.calendar.rob_dunmires_facebook_events.attributes.message }}

