- platform: template
  sensors:
    time_brightness:
      value_template: >-
        {%- if now().strftime('%H%M')|int < 530 -%}
          80
        {%- elif now().strftime('%H%M')|int < 700 -%}
          128
        {%- elif now().strftime('%H%M')|int < 800 -%}
          192
        {%- elif now().strftime('%H%M')|int < 2000 -%}
          255
        {%- elif now().strftime('%H%M')|int < 2100 -%}
          192
        {%- elif now().strftime('%H%M')|int < 2200 -%}
          128
        {%- else -%}
          64
        {%- endif -%}
