- platform: template
  sensors:
    time_brightness:
      value_template: >-
        {%- if now().strftime('%H%M')|int < 530 -%}
          70
        {%- elif now().strftime('%H%M')|int < 700 -%}
          100
        {%- elif now().strftime('%H%M')|int < 800 -%}
          120
        {%- elif now().strftime('%H%M')|int < 2000 -%}
          200
        {%- elif now().strftime('%H%M')|int < 2100 -%}
          120
        {%- elif now().strftime('%H%M')|int < 2200 -%}
          80
        {%- else -%}
          60
        {%- endif -%}
