- platform: template
  sensors:
    front_hall_motion_sensor:
      friendly_name: Front Hall Motion Sensor
      value_template: >-
        {%- if is_state('sensor.front_door_motion_light_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.front_door_motion_light_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.front_door_motion_light_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.front_door_motion_light_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}
    garage_inside_motion_sensor:
      friendly_name: Garage Inside Motion Sensor
      value_template: >-
        {%- if is_state('sensor.garage_inside_motion_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.garage_inside_motion_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.garage_inside_motion_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.garage_inside_motion_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}

