- platform: template
  sensors:
    dining_room_motion_sensor:
      friendly_name: Dining Room
      value_template: >-
        {%- if is_state('sensor.dining_room_light_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.dining_room_light_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.dining_room_light_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.dining_room_light_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}

    front_hall_motion_sensor:
      friendly_name: Front Hall
      value_template: >-
        {%- if is_state('sensor.front_door_light_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.front_door_light_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.front_door_light_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.front_door_light_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}
    family_room_motion_sensor:
      friendly_name: Family Room
      value_template: >-
        {%- if is_state('sensor.patio_plug_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.patio_plug_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.patio_plug_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.patio_plug_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}
    kids_room1_motion_sensor:
      friendly_name: Brayden's Room
      value_template: >-
        {%- if is_state('sensor.kids_room1_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.kids_room1_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.kids_room1_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.kids_room1_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}
    kids_room2_motion_sensor:
      friendly_name: Ana's Room
      value_template: >-
        {%- if is_state('sensor.kids_room2_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.kids_room2_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.kids_room2_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.kids_room2_burglar', '254') -%}
          OK
        {%- else -%}
          OK
        {%- endif -%}
    garage_inside_motion_sensor:
      friendly_name: Garage Inside
      value_template: >-
        {%- if is_state('sensor.garage_inside_motion_burglar', '3') -%}
          Tamper
        {%- elif is_state('sensor.garage_inside_motion_burglar', '8') -%}
          Motion
        {%- elif is_state('sensor.garage_inside_motion_burglar', '0') -%}
          OK
        {%- elif is_state('sensor.garage_inside_motion_burglar', '254') -%}
          OK
        {%- else -%}
          Unknown
        {%- endif -%}
    template_last_motion:
        friendly_name: 'Last Motion'
        value_template: >
          {%- set sensors = [states.sensor.garage_inside_motion_sensor, states.sensor.kids_room1_motion_sensor, states.sensor.family_room_motion_sensor, states.sensor.front_hall_motion_sensor] %}
          {% for sensor in sensors %}
            {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
              {{ sensor.name }}
            {% endif %}
          {% endfor %}
