- platform: template
  sensors:
    occupancy_house:
      friendly_name: House Occupied
      value_template: >-
        {%- if is_state('binary_sensor.house_occupied', 'on') -%}
          Yes
        {%- else -%}
          No
        {%- endif -%}
    occupancy_robert:
      friendly_name: Robert Home
      value_template: >-
        {%- if is_state('device_tracker.robert_phone', 'home') -%}
          Yes
        {%- else -%}
          No
        {%- endif -%}
