- platform: snmp
  name: Online
  host: !secret mikrotik_host
  community: !secret mikrotik_snmp
  version: 2c
  baseoid: 1.3.6.1.4.1.14988.1.1.18.1.1.2.2
  accept_errors: true
  default_value: 0
  scan_interval: 60

- platform: template
  sensors:
    internet:
      friendly_name: Internet Access
      value_template: >-
        {%- if is_state('sensor.online', '1') -%}
          In Use
        {%- else -%}
          Idle
        {%- endif -%}

