- platform: google_travel_time
  name: Home to Work
  api_key: !secret google_maps_api_key
  origin: Home
  destination: I-Evolve

- platform: google_travel_time
  name: Robs ETA To Home
  api_key: !secret google_maps_api_key
  origin: device_tracker.robert_phone
  destination: Home

- platform: google_travel_time
  name: Work to I90
  api_key: !secret google_maps_api_key
  origin: I-Evolve
  destination: I90

- platform: google_travel_time
  name: I90 to Home
  api_key: !secret google_maps_api_key
  origin: I90
  destination: Home

- platform: google_travel_time
  name: Work to Hopkins
  api_key: !secret google_maps_api_key
  origin: I-Evolve
  destination: Hopkins and Maple

- platform: google_travel_time
  name: Hopkins to Home
  api_key: !secret google_maps_api_key
  origin: Hopkins and Maple
  destination: Home
