- platform: template
  sensors:
    away_mode:
      friendly_name: "Away Mode"
      delay_on:
          minutes: 15
      delay_off:
          minutes: 1
      entity_id:
        - binary_sensor.house_occupied
      value_template: >-
        {{ is_state('binary_sensor.house_occupied', 'off') }}

