- platform: template
  sensors:
    away_mode:
      friendly_name: "Away Mode"
      delay_on:
          minutes: 10
      delay_off:
          minutes: 2
      value_template: >-
        {{ is_state('binary_sensor.house_occupied', 'off') }}

