- platform: template
  sensors:
    house_occupied:
      friendly_name: "House Occupied"
      delay_on:
          minutes: 2
      delay_off:
          minutes: 5
      entity_id:
        - device_tracker.ana_phone
        - device_tracker.robert_phone
        - device_tracker.robert_phone_bt
        - device_tracker.sarah_phone
        - device_tracker.sarah_phone_bt
        - binary_sensor.tv_in_use
        - sensor.dining_room_light_burglar
        - sensor.half_bathroom_burglar
        - sensor.front_door_light_burglar
        - sensor.patio_plug_burglar
        - sensor.kids_room1_burglar
      value_template: >-
        {{ is_state('device_tracker.ana_phone', 'home')
        or is_state('device_tracker.robert_phone', 'home')
        or is_state('device_tracker.robert_phone_bt', 'home')
        or is_state('device_tracker.sarah_phone', 'home')
        or is_state('device_tracker.sarah_phone_bt', 'home')
        or is_state('binary_sensor.tv_in_use', 'on')
        or is_state('sensor.dining_room_light_burglar', '8')
        or is_state('sensor.half_bathroom_burglar', '8')
        or is_state('sensor.front_door_light_burglar', '8')
        or is_state('sensor.patio_plug_burglar', '8')
        or is_state('sensor.kids_room1_burglar', '8')}}


    robert_home:
      friendly_name: "Robert is home"
      delay_off:
          minutes: 1
      entity_id:
        - device_tracker.robert_phone
        - device_tracker.robert_phone_bt
        - device_tracker.robert_phone_wifi
      value_template: >-
        {{ is_state('device_tracker.robert_phone', 'home')
        or is_state('device_tracker.robert_phone_bt', 'home')
        or is_state('device_tracker.robert_phone_wifi', 'home') }}


