- platform: template
  sensors:
    house_occupied:
      friendly_name: "House Occupied"
      delay_on:
          minutes: 2
      delay_off:
          minutes: 15
      value_template: >-
        {{ is_state('device_tracker.ana_phone', 'home')
        or is_state('device_tracker.robert_phone', 'home')
        or is_state('device_tracker.robert_phone_bt', 'home')
        or is_state('device_tracker.sarah_phone', 'home')
        or is_state('device_tracker.sarahs_iphone', 'home')
        or is_state('binary_sensor.tv_in_use', 'on')
        or is_state('sensor.dining_room_light_burglar', '8')
        or is_state('sensor.half_bathroom_burglar', '8')
        or is_state('sensor.front_door_light_burglar', '8')
        or is_state('sensor.patio_plug_burglar', '8')
        or is_state('sensor.kids_room1_burglar', '8') }}

    robert_home:
      friendly_name: "Robert is home"
      delay_off:
          minutes: 1
      value_template: >-
        {{ is_state('device_tracker.robert_phone', 'home')
        or is_state('device_tracker.robert_phone_bt', 'home')
        or is_state('device_tracker.robert_phone_wifi', 'home') }}


