- platform: template
  sensors:
    quiet_time:
      friendly_name: "Quiet Time"
      entity_id:
        - sensor.time
        - binary_sensor.workday_sensor
      value_template: >-
        {{ ( now().hour < 7 ) 
        or ( now().hour > 19 ) }}

#or ( states.binary_sensor.workday_sensor == "off" and now().hour < 9 )

