- alias: 'Lights - Away Mode Night'
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupied
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: "01:22:00"
  action:
    service: scene.turn_on
    entity_id: scene.away_lights

- alias: 'Quiet Time - Arrive Home Late'
  condition:
    - condition: time
      after: '20:00:00'
      before: '23:59:59'
    - condition: state
      entity_id: binary_sensor.quiet_time
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.house_occupied
    to: 'on'
  action:
    - delay: '00:10:01'
    - service: script.turn_on
      entity_id: script.quiet_on
 
# ====================================================

- alias: 'Outside Lights turn on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:12:00"
    - platform: sun
      event: sunrise
      offset: "-01:12:34"
  action:
    - service: switch.turn_on
      entity_id: switch.front_outside_lights_switch
    - service: switch.turn_on
      entity_id: switch.basement_wall_plug_switch

- alias: 'Outside Lights turn off'
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
  trigger:
      - platform: time
        at: '00:23:10'
      - platform: sun
        event: sunrise
        offset: "00:12:00"
  action:
    - service: switch.turn_off
      entity_id: switch.front_outside_lights_switch
    - service: switch.turn_off
      entity_id: switch.basement_wall_plug_switch

- alias: 'Seasonal Outside Lights turn off'
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
  trigger:
      - platform: time
        at: '21:21:10'
  action:
    service: switch.turn_off
    entity_id: switch.basement_wall_plug_switch


- alias: 'Family Room Lights turn off'
  trigger:
    platform: state
    entity_id: binary_sensor.family_rm_occupied
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
    - condition: state
      entity_id: light.family_room_level
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: light.family_room_level

- alias: 'Stairs Lights turn off'
  trigger:
    platform: state
    entity_id: binary_sensor.front_hall_occupied
    to: 'off'
    for:
      minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.disable_auto_lights
      state: 'off'
    - condition: state
      entity_id: light.stairs_light_level
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: light.stairs_light_level


# ====================================================


