- alias: Unexpected Motion Garage
  trigger:
    platform: state
    entity_id: sensor.garage_inside_motion_burglar
    to: '8'
  condition:
    - condition: state
      entity_id: input_boolean.disable_unexpected_motion_notification
      state: 'off'
    - condition: state
      entity_id: binary_sensor.robert_home
      state: 'off'
  action:
    service: notify.homepird3scom_html5_robert_phone
    data:
      message: 'Unexpected Motion in {{ trigger.to_state.attributes.friendly_name }}'



