- alias: Turn kitchen lights Motion 
  trigger:
    platform: state
    entity_id: sensor.front_hall_motion_sensor
    to: 'Motion'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.house_occupied
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.kitchen_table_light_level
#    data:
#        brightness: '{{ states.sensor.time_brightness.state|int }}'

- alias: Unexpected Motion Garage
  trigger:
    platform: state
    entity_id: sensor.garage_inside_motion_burglar
    to: '8'
  condition:
    - condition: state
      entity_id: input_boolean.disable_unexpected_motion_notification
      state: 'off'
    - condition: state
      entity_id: binary_sensor.robert_home
      state: 'off'
  action:
    service: notify.homepird3scom_html5_robert_phone
    data:
      message: 'Unexpected Motion in {{ trigger.to_state.attributes.friendly_name }}'



