- alias: Unexpected Motion Garage
  trigger:
    platform: state
    entity_id: binary_sensor.garage_occupied
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.disable_unexpected_motion_notification
      state: 'off'
    - condition: state
      entity_id: binary_sensor.robert_home
      state: 'off'
  action:
    service: notify.homepird3scom_html5_robert_phone
    data_template:
      message: 'Unexpected Motion in {{ trigger.to_state.attributes.friendly_name }}'

# Update Last Motion variable
- alias: "Update Last Motion"
  trigger:
    - platform: state
      entity_id: sensor.family_room_motion_sensor, sensor.front_hall_motion_sensor, sensor.dining_room_motion_sensor, sensor.garage_inside_motion_sensor, sensor.kids_room1_motion_sensor
      to: 'Motion'
  action:
    - service: variable.set_variable
      data:
        variable: last_motion
        attributes_template: >
            {
              "history_1": "{{ variable.state }}",
              "history_2": "{{ variable.attributes.history_1 }}",
              "history_3": "{{ variable.attributes.history_2 }}"
            }
      data_template:
        value: "{{ trigger.to_state.attributes.friendly_name }}"

