- alias: 'House Night Auto Lights Off'
  trigger:
    platform: time
    at: '23:05:00'
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupied
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.good_night

- alias: 'House Night TV Auto Off'
  trigger:
    platform: time
    at: '23:15:00'
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupied
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_tomorrow
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_device_auto_off
      state: 'off'
  action:
    service: script.turn_on
    entity_id: script.devices_off

- alias: 'House Late Night Auto Off'
  trigger:
    platform: time
    at: '01:15:00'
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupied
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_device_auto_off
      state: 'off'
  action:
    service: script.turn_on
    entity_id: script.devices_off


