- alias: Notify When Battery Low
  trigger:
    platform: numeric_state
    entity_id: sensor.thermostat_battery
    below: '20'
  action:
    service: notify.homepird3scom
    data_template:
      message: 'Thermostat Has Low Battery'
