- alias: 'Home - Away Mode'
  trigger:
    platform: state
    entity_id: binary_sensor.away_mode
    to: 'on'
  condition:
    condition: time
    after: '07:00:00'
    before: '18:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.home_away

- alias: 'Home - Occupied Mode'
  trigger:
    platform: state
    entity_id: binary_sensor.away_mode
    to: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.home_occupied


