- alias: 'Time at HA startup'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: '00:00:24'
    - service:  tts.google_say
      entity_id: media_player.homepi_audio
      data_template:
        message: "It is now {{ now().strftime('%I %M %p') }} and {{ states('sensor.pws_temp_f') }} degrees outside."


- alias: 'Speak current time and tempature'
  trigger:
   - platform: time
     minutes: '00'
     seconds: '00'
  condition:
   - condition: state
     entity_id: input_boolean.disable_current_time_temp_notification
     state: 'off'
   - condition: state
     entity_id: binary_sensor.quiet_time
     state: 'off'
  action:
    - delay: '00:00:03'
    - service: tts.google_say
      entity_id: media_player.homepi_audio
      data_template:
        message: "It is now {{ now().strftime('%I %p') }} and {{ states('sensor.pws_temp_f') }} degrees outside."

